version: "3.1"

services:
  # app:
  #   build:
  #    context: ./
  #   ports:
  #     - 3000:3000

  # tor:
  #   image: osminogin/tor-simple
  #   restart: always

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
